// Code generated by candi v1.6.4.

package main

import (
	"log"

	shareddomain "be-shark/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candihelper"
	"pkg.agungdp.dev/candi/config/database"
	"pkg.agungdp.dev/candi/config/env"

	_ "github.com/lib/pq"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

func main() {
	env.Load("be-shark")
	sqlDeps := database.InitSQLDatabase()
	gormWrite, err := gorm.Open(postgres.New(postgres.Config{
		Conn: sqlDeps.WriteDB(),
	}), &gorm.Config{})
	if err != nil {
		log.Fatal(err)
	}
	gormWrite.AutoMigrate(
		&shareddomain.Account{},
		&shareddomain.Contact{},
	)
	log.Printf("\x1b[32;1mMigration to \"%s\" suceess\x1b[0m\n", candihelper.MaskingPasswordURL(env.BaseEnv().DbSQLWriteDSN))
}
