// Code generated by candi v1.6.4.

package usecase

import (
	"context"

	shareddomain "be-shark/pkg/shared/domain"

	"pkg.agungdp.dev/candi/candishared"
)

// AccountUsecase abstraction
type AccountUsecase interface {
	GetAllAccount(ctx context.Context, filter candishared.Filter) (data []shareddomain.Account, meta candishared.Meta, err error)
	GetDetailAccount(ctx context.Context, id string) (data shareddomain.Account, err error)
	CreateAccount(ctx context.Context, data *shareddomain.Account) (err error)
	UpdateAccount(ctx context.Context, id string, data *shareddomain.Account) (err error)
	DeleteAccount(ctx context.Context, id string) (err error)
}
