// Code generated by candi v1.6.4.

package domain

import (
	"time"
)

// Contact model
type Contact struct {
	ID         string    ` json:"id"`
	Field      string ` json:"field"`
	CreatedAt  time.Time ` json:"created_at"`
	ModifiedAt time.Time ` json:"modified_at"`
}	
