// Code generated by candi v1.6.4.

package repository

import (
	"context"

	"pkg.agungdp.dev/candi/candishared"
	shareddomain "be-shark/pkg/shared/domain"
)

// ContactRepository abstract interface
type ContactRepository interface {
	FetchAll(ctx context.Context, filter *candishared.Filter) ([]shareddomain.Contact, error)
	Count(ctx context.Context, filter *candishared.Filter) int
	Find(ctx context.Context, data *shareddomain.Contact) error
	Save(ctx context.Context, data *shareddomain.Contact) error
	Delete(ctx context.Context, id string) (err error)
}
