// Code generated by candi v1.6.4.

package repository

import (
	"context"

	"pkg.agungdp.dev/candi/candishared"
	shareddomain "be-shark/pkg/shared/domain"
)

// AccountRepository abstract interface
type AccountRepository interface {
	FetchAll(ctx context.Context, filter *candishared.Filter) ([]shareddomain.Account, error)
	Count(ctx context.Context, filter *candishared.Filter) int
	Find(ctx context.Context, data *shareddomain.Account) error
	Save(ctx context.Context, data *shareddomain.Account) error
	Delete(ctx context.Context, id string) (err error)
}
