// Code generated by candi v1.6.4.

package resthandler

import (
	"net/http"

	"github.com/labstack/echo"

	shareddomain "be-shark/pkg/shared/domain"
	"be-shark/pkg/shared/usecase"

	"pkg.agungdp.dev/candi/candihelper"
	"pkg.agungdp.dev/candi/candishared"
	"pkg.agungdp.dev/candi/codebase/interfaces"
	"pkg.agungdp.dev/candi/tracer"
	"pkg.agungdp.dev/candi/wrapper"
)

// RestHandler handler
type RestHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewRestHandler create new rest handler
func NewRestHandler(mw interfaces.Middleware, uc usecase.Usecase, validator interfaces.Validator) *RestHandler {
	return &RestHandler{
		mw: mw, uc: uc, validator: validator,
	}
}

// Mount handler with root "/"
// handling version in here
func (h *RestHandler) Mount(root *echo.Group) {
	v1Root := root.Group(candihelper.V1)

	contact := v1Root.Group("/contact", echo.WrapMiddleware(h.mw.HTTPBearerAuth))
	contact.GET("", h.getAllContact, echo.WrapMiddleware(h.mw.HTTPPermissionACL("resource.public")))
	contact.GET("/:id", h.getDetailContactByID, echo.WrapMiddleware(h.mw.HTTPPermissionACL("resource.public")))
	contact.POST("", h.createContact, echo.WrapMiddleware(h.mw.HTTPPermissionACL("resource.public")))
	contact.PUT("/:id", h.updateContact, echo.WrapMiddleware(h.mw.HTTPPermissionACL("resource.public")))
	contact.DELETE("/:id", h.deleteContact, echo.WrapMiddleware(h.mw.HTTPPermissionACL("resource.public")))
}

func (h *RestHandler) getAllContact(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "ContactDeliveryREST:GetAllContact")
	defer trace.Finish()

	tokenClaim := candishared.ParseTokenClaimFromContext(ctx) // must using HTTPBearerAuth in middleware for this handler

	var filter candishared.Filter
	if err := candihelper.ParseFromQueryParam(c.Request().URL.Query(), &filter); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	data, meta, err := h.uc.Contact().GetAllContact(ctx, filter)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusOK, err.Error()).JSON(c.Response())
	}

	message := "Success, with your user id (" + tokenClaim.Subject + ") and role (" + tokenClaim.Role + ")"
	return wrapper.NewHTTPResponse(http.StatusOK, message, meta, data).JSON(c.Response())
}

func (h *RestHandler) getDetailContactByID(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "ContactDeliveryREST:GetDetailContactByID")
	defer trace.Finish()

	data, err := h.uc.Contact().GetDetailContact(ctx, c.Param("id"))
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success", data).JSON(c.Response())
}

func (h *RestHandler) createContact(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "ContactDeliveryREST:CreateContact")
	defer trace.Finish()

	var payload shareddomain.Contact
	if err := c.Bind(&payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusOK, err.Error()).JSON(c.Response())
	}

	err := h.uc.Contact().CreateContact(ctx, &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}

func (h *RestHandler) updateContact(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "ContactDeliveryREST:UpdateContact")
	defer trace.Finish()

	var payload shareddomain.Contact
	if err := c.Bind(&payload); err != nil {
		return wrapper.NewHTTPResponse(http.StatusOK, err.Error()).JSON(c.Response())
	}

	err := h.uc.Contact().UpdateContact(ctx, c.Param("id"), &payload)
	if err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}

func (h *RestHandler) deleteContact(c echo.Context) error {
	trace, ctx := tracer.StartTraceWithContext(c.Request().Context(), "ContactDeliveryREST:DeleteContact")
	defer trace.Finish()

	if err := h.uc.Contact().DeleteContact(ctx, c.Param("id")); err != nil {
		return wrapper.NewHTTPResponse(http.StatusBadRequest, err.Error()).JSON(c.Response())
	}

	return wrapper.NewHTTPResponse(http.StatusOK, "Success").JSON(c.Response())
}
